<?php

/**
 * ProcessWire Textile Textformatter
 *
 * ProcessWire 2.x 
 * Copyright (C) 2012 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 * T E X T I L E
 * Copyright (c) 2003-2004, Dean Allen <dean@textism.com>
 * All rights reserved.
 * Thanks to Carlo Zottmann <carlo@g-blog.net> for refactoring
 * Textile's procedural code into a class framework
 * Additions and fixes Copyright (c) 2006    Alex Shiels       http://thresholdstate.com/
 * Additions and fixes Copyright (c) 2010    Stef Dawson       http://stefdawson.com/
 * Additions and fixes Copyright (c) 2010-12 Netcarver         http://github.com/netcarver
 * Additions and fixes Copyright (c) 2011    Jeff Soo          http://ipsedixit.net
 * Additions and fixes Copyright (c) 2012    Robert Wetzlmayr  http://wetzlmayr.com/
 *
 */

class TextformatterTextile extends Textformatter {

	public static function getModuleInfo() {
		return array(
			'title' => 'Textile', 
			'version' => 230, 
			'summary' => "Textile text formatting from Textpattern by Dean Allen with additions by Alex Shiels. For use with trusted input only.", 
			'url' => "http://en.wikipedia.org/wiki/Textile_(markup_language)", 
		); 
	}

	public function format(&$str) {
		require_once($this->config->paths->TextformatterTextile . 'classTextile.php'); 
		$textile = new Textile();
		$str = $textile->TextileThis($str); 
	}
}
